
CXX = g++
CXXFLAG = -std=c++17 -I../googletest/googletest/include/
LDFLAG = -L../googletest/lib/ -l gtest -l gtest_main

all: 1 2 3 4

1: 1.cpp
	g++ 1.cpp ${CXXFLAG} ${LDFLAG} -o 1
2: 2.cpp
	g++ 2.cpp ${CXXFLAG} ${LDFLAG} -o 2
3: 3.cpp
	g++ 3.cpp ${CXXFLAG} ${LDFLAG} -o 3
4: 4.cpp
	g++ 4.cpp ${CXXFLAG} ${LDFLAG} -o 4
